### ISSUE TITLE
Take input of image 

### ISSUE THREAD

**Issue by kunal90803** [kunal90803/OCR_IDE#3]
.. as a screenshot of variable dimension like snipping tool

**Comment by Omksaini2003** [comment]
assign me this issue asap

**Comment by Omksaini2003** [comment]
we cant add snipping tool like feature that can take snips from different tabs as its not allowed due to browser as well as native security reasons,

**Comment by Omksaini2003** [comment]
however we can build a chrome extension which has access to tabs and can take snips from anytab inside browser.
